/** Generated by scripts/apply-backend-origin.cjs from BACKEND_ORIGIN (.env or env var) */
export const environment = {
  production: true,
  apiOrigin: "http://192.168.29.28:3000",
  ssrApiOrigin: "http://192.168.29.28:3000"
};
