/** Generated by scripts/apply-backend-origin.cjs from BACKEND_ORIGIN (.env or env var) */
export const environment = {
  production: true,
  apiOrigin: "http://127.0.0.1:3000",
  ssrApiOrigin: "http://127.0.0.1:3000",
};
